# Generated by Django 3.2.6 on 2021-08-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postmodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
